FROM mkoch/base
MAINTAINER Michael Koch <michael.koch@enough.de>

RUN \
	echo 'deb http://httpredir.debian.org/debian stretche-backports main' >> /etc/apt/sources.list.d/backports.list && \
	rm -rf /var/lib/apt/lists/*

